conjurdemos/kubernetes-conjur-demo

1_create_test_app_namespace.sh
kubernetes/test-app-conjur-authenticator-role-binding.yml
openshift/test-app-conjur-authenticator-role-binding.yml

To avoid collisions in scripts running at the same time, append the Conjur
namespace to the conjur-authenticator ClusterRole and binding

Update ClusterRole / binding to append namespace

---

.gitignore
7_verify_authentication.sh
Jenkinsfile
ci/Dockerfile
ci/platform_login
ci/secrets.yml
ci/test
utils.sh

Resolves #26 
Add a Jenkins pipeline to this repository that will run the start scripts and fail on error.
Currently only GKE is supported, with plans to support OpenShift in the future.
Also updates the verification script so that it will wait until the service is available before performing the verification check.
[green build](https://jenkins.conjur.net/job/conjurdemos--kubernetes-conjur-demo/job/26-add-gke-test-to-jenkins/24/)
To get the build green, I had to temporarily hardcode the v5 appliance to 5.1.2 (5.0-stable sometimes is not working in K8s right now).
Please do not squash merge.

Adding Jenkins pipeline

---

5_build_and_push_containers.sh
6_deploy_test_app.sh
7_verify_authentication.sh
openshift/test-app-summon-init.yml
openshift/test-app-summon-sidecar.yml
policy/templates/project-authn-def.template.yml
start
stop
utils.sh
webapp/secrets.yml
webapp/webapp_v5.sh

Note: this build is expected to fail because there is still a bug in `cyberark/conjur` that impacts the Secretless flow in GKE (see https://github.com/cyberark/conjur/issues/762)

Updates to get demo working with OpenShift 3.9

---

5_build_and_push_containers.sh
6_deploy_test_app.sh
README.md
kubernetes/test-app-summon-init.yml
kubernetes/test-app-summon-sidecar.yml
utils.sh

When the LOCAL_AUTHENTICATOR env var is set to true, the scripts will use a
local authenticator client image to deploy the test apps.

Enable running with local authenticator build

---

2_load_conjur_policies.sh
6_deploy_test_app.sh
README.md
bootstrap.env
policy/load_policies.sh
set_env_vars.sh
start
utils.sh

- Separate env var default setting into its own script that can be imported in
start and utils.sh
- Augment existing bootstrap.env
- Update README with instructions for standard (only followers in k8s) flow,
with the master-in-k8s flow as a special case
- Add a convenience script to enable loading the demo policies in a CLI
container connected to a remote master
Connected to conjurinc/appliance#606
Verified master+followers flow and follower-only flow in GKE and OC 3.9

Update scripts to enable follower-only in k8s flow

---

6_deploy_test_app.sh
Jenkinsfile
ci/secrets.yml
ci/test
policy/templates/project-authn-def.template.yml
utils.sh

Adds support for running CI tests for OpenShift
Resolves #43 
TODO: rollback tempfix commits once

add support for openshift ci

---

utils.sh

It's not clear why but occasionally the previous form would result in a failed build with the message:
```
Got 'postgres', expected TEST_APP_DATABASE to be one of:
'postgres'
'mysql'
```
This suggested the condition check logic might be flawed.

cleanup ensure_env_database

---

utils.sh

We had transient failures in the timed wait loop that was caused by a
wait command that succeeded then failed right after so now we ensure
that on success we return as soon as we pass the condition.

Fix intermittent build failures with waiting on pods

---

utils.sh

Either deploy nor demo explicitly need to set this variable so in
non-minienv cases this util class will fail. This fix ensures that we
assume that minienv is false when it's not set.

Ensure that MINI_ENV variable has variable value set

---

.gitleaks.toml
policy/load_policies.sh

- Add gitleaks config to project (ignoring a single sample PEM file)
- Update the way the DB info is stored in Conjur to reflect differences in how the app connects to the DB for the authenticator sidecar vs Secretless
Note for reviewer: it's expected that the build will be green and the error referenced below will not surface, but I have verified that using a local build of the latest code on Secretless master works with these changes.
Connected to cyberark/secretless-broker#818

Minor querystring update

---

policy/templates/authn-any-policy-branch.template.yml

The annotation value was `cyberark-secrets-provider` while the actual container that the authentication was done from is `authenticator`.

Fix authentication-container-name annotation value

---

.gitmodules
7_verify_authentication.sh
start
utils.sh

Previously these loops could be infinite if their exit conditions were not
met. This commit introduces the retry function from bash-lib, ensuring
that only a finite number of attempts will be made.
Related: conjurinc/ops#423

Limit retries in 7_verify_auth loops

---

utils.sh

This _may_ resolve the intermittent issue where it looked like the string
'postgres' didn't match 'postgres', but should provide a better representation
of the string contents if it doesn't match

Adjust test app database type to be more accurate and have better logging

---

kubernetes/mysql.template.yml
kubernetes/postgres.template.yml
kubernetes/test-app-conjur-authenticator-role-binding.yml
kubernetes/test-app-secretless.yml
kubernetes/test-app-summon-init.yml
kubernetes/test-app-summon-sidecar.yml
kubernetes/test-app-with-host-outside-apps-branch-summon-init.yml
openshift/mysql.template.yml
openshift/postgres.template.yml
openshift/test-app-conjur-authenticator-role-binding.yml

Based on the Secretless MSSQL XA (cyberark/secretless-broker#977) we have a recommended update to the API versioning we use in this demo repo / in the docs.
This PR updates the demo flows to use API `v1` instead of `v1beta1`

Updates to use API v1 instead of v1beta1

---

0_check_dependencies.sh
2_load_conjur_policies.sh
6_deploy_test_app.sh
README.md
policy/templates/authn-any-policy-branch.template.yml
policy/templates/project-authn-def.template.yml
set_env_vars.sh
utils.sh

This change includes the following:
- Adds URL encoding for the Kubernetes authentication ID so that forwarding
works for values with slashes such as `openshift/dap-support-19`.
- Adds support for optionally using an application's deployment name (rather
than service account name) when authenticating with Kubernetes. This is
enabled by setting the following environment:
```
export CONJUR_AUTHN_LOGIN_RESOURCE=deployment
```
The default is to use service account name when authenticating with
Kubernetes.
- Fixes settings for openshift vs. kubernetes operation in the
policy template to reflect what is set for the PLATFORM environment
variable. For example, if PLATORM is set to "kubernetes", then
the policy templates will render with the following lines:
```
`openshift: "false"`
`kubernetes: …
```

Fixes URL encoding for Kubernetes authentication ID

---

6_deploy_test_app.sh

The image `cyberark/conjur-kubernetes-authenticator` will be deprecated in the future.
We should use the new name `conjur-authn-k8s-client` in our tests.

Change image name to new name

---

README.md
ci/test
kubernetes/test-app-secretless.yml
kubernetes/test-app-summon-init.yml
kubernetes/test-app-summon-sidecar.yml
kubernetes/test-app-with-host-outside-apps-branch-summon-init.yml
openshift/test-app-secretless.yml
openshift/test-app-summon-init.yml
openshift/test-app-summon-sidecar.yml
openshift/test-app-with-host-outside-apps-branch-summon-init.yml

The parameter `CONJUR_VERSION` is not required anymore in the
`conjur-authn-k8s-client` and is defaulted to `5`. We should remove
them from this project too when we deploy pods of the `conjur-authn-k8s-client`
and the `secretless-broker` to verify that it is indeed not required.

Remove redundant CONJUR_VERSION parameter

---

kubernetes/test-app-with-host-outside-apps-branch-summon-init.yml
openshift/test-app-summon-init.yml
openshift/test-app-summon-sidecar.yml
openshift/test-app-with-host-outside-apps-branch-summon-init.yml

The authn-k8s client image does not require the appliance URL to be able to
authenticate with Conjur. In this commit, we remove the appliance URLs from the
Authenticator containers.
Note that the _app_ container will still need the appliance URL to authenticate
with Conjur via the default authenticator, once the access token is available
to the application.
Secretless also still needs the appliance URL, since it instantiates the Go
client using the access token it retrieves via Kubernetes authentication.

Remove CONJUR_APPLIANCE_URL from authenticator image

---

ci/test

We have the ability to set CONJUR_LOG_LEVEL in the env so
when we deploy Conjur it will also set the log level of the
DAP cluster to the given level. TO enable this feature in this project
we need to pass the variable in the Docker command to the container
that will run the Conjur deployment

Pass CONJUR_LOG_LEVEL env var to docker container

---

ci/secrets.yml
ci/test

[This PR](https://github.com/cyberark/kubernetes-conjur-deploy/pull/137) added the use
of the TEST_PLATFORM env var in the `./start.sh` script that is used in this repo.
This means that we need to set and pass this variable when running the script. Please see [this comment](https://github.com/cyberark/kubernetes-conjur-deploy/pull/137#discussion_r484049147) on the other PR that stated why this 
PR is needed and why this is not the optimal solution.

Set and pass TEST_PLATFORM env var to docker container

---

Jenkinsfile
policy/templates/project-authn-def.template.yml

The current CI test cases test authn-k8s on OpenShift platforms using host-ID-based
authentication. This change adds test cases for testing authn-k8s on OpenShift using
DAP and the newer-style, annotation-based authentication, where the Kubernetes
resources being authenticated are configured as annotations on the host definition
in the Conjur policy.
NOTE: The annotation-based tests that are being added do not include the use of
the OpenShift `DeploymentConfigs` resources as application identity. This will be
addressed with the following:
- https://github.com/cyberark/kubernetes-conjur-deploy/pull/158
- https://github.com/conjurdemos/kubernetes-conjur-demo/issues/115
- https://github.com/conjurdemos/kubernetes-conjur-demo/pull/112
Addresses Issue #109

Adds CI for testing annotation-based authn on OpenShift with DAP

---

ci/secrets.yml
ci/test

The kubernetes-conjur-deploy project now expects this environment variable to determine how it should deploy the Conjur or DAP server to test against. This allows it to account for changes from OC 3 to OC 4.
See: https://github.com/cyberark/kubernetes-conjur-deploy/pull/163
Connected to https://github.com/conjurinc/appliance/issues/1486

Add OPENSHIFT_VERSION to test environments

---

stop
utils.sh

This change adds:
- A workaround for an OpenShift 4.3 bug (https://bugzilla.redhat.com/show_bug.cgi?id=1798282)
whereby deleting a namespace may hang indefitely because sometimes finalizers are left undeleted
on Kubernetes services in the namespace.
- A display of residual Kubernetes resources when namespace delete fails.
NOTE: Jenkins tests are currently failing on OpenShift 4.5. This failure is unrelated to the change
being made here. The failures for OpenShift 4.5 appear could possibly be due to improper
credentials being set for this routine in platform_login:
```
elif [[ "$PLATFORM" = "openshift" ]]; then
oc login $OPENSHIFT_URL \
--username=$OPENSHIFT_USERNAME \
--password=$OPENSHIFT_PASSWORD \
--insecure-skip-tls-verify=true
docker login \
-u _ -p "$(oc whoami -t)" \ …
```

Eliminates hanging on namespace deletion for OpenShift 4.3

---

stop

In the stop script, there is a check for the value of the `$OPENSHIFT_VERSION`
without first checking that the `$PLATFORM` environment variable is set to
"openshift". This can result in a undefined variable error for
`$OPENSHIFT_VERSION`.
This change adds a check that `$PLATFORM` is set to "openshift" before
checking `$OPENSHIFT_VERSION` value.

Adds check for platform before checking OPENSHIFT_VERSION

---

ci/secrets.yml
ci/test
stop

OpenShift Version 4.3 has a known bug whereby deletion of services
that use LoadBalancers (or namespaces that contain such services)
can cause indefinite hanging. Apparently there are finalizers used
on these services to force cleanup of loadbalancer resources, and
the finalizers are never deleted from the service:
https://bugzilla.redhat.com/show_bug.cgi?id=1798282
This change disables the use of LoadBalancers for the OpenShift 4.3
testing as a temporary workaround.
NOTE: There is a similar change required in the cyberark/kubernetes-conjur-deploy
since Conjur is being deployed with services that use LoadBalancers. The change
that we come up for cyberark/kubernetes-conjur-deploy will probably need
an environment variable setting in the CI builds in this demo repo for OC 4.3.
That work …

Removes loadbalancers for OC 4.3 tests to eliminate hangs

---

Jenkinsfile
ci/secrets.yml
ci/test

This removes the hard coded Openshift versions and uses oldest, current, and next.
This also adds a flow to the Jenkinsfile for next, so next will not be run unless
you pick the option in the Jenkins UI.
Below is a view of a Jenkins run using the current and oldest, next is not run in this view as 
the option is not selected in the UI for a git push.
Note: #131 should go in first, then this issue will be updated. 
Addresses issue #128

Remove hardcoded OCP versions and replace with oldest, current and next.

---

5_app_store_conjur_cert.sh
Jenkinsfile
ci/Dockerfile
ci/test

1. Adds a logical branch for deploying Conjur OSS via Helm on OpenShift, instead of using kubernetes-conjur-deploy. 
TODO: it's probably better to move this functionality to kubernetes-conjur-deploy. 
TODO: there really needs to be a better way of passing along conjur config to kubernetes-conjur-demo (fortunately we're working on this). At present kubernetes-conjur-demo seems too tightly coupled with kubernetes-conjur-deploy and knows too much about it, this makes it more difficult to make updates to either.
2. Adds flows to Jenkinsfile for test authn-k8s on Conjur-OSS deployed via Helm chart on OpenShift (using both host-ID-based and annotation-based identity.)
Resolves #110

Test authn-k8s on Conjur-OSS deployed via Helm chart on OpenShift

---

5_app_store_conjur_cert.sh
ci/test

The scripts currently require that the environment variable `CONJUR_OSS_HELM_RELEASE` be set. This environment variable is set in our CI test scripts, but typical users of these scripts would not be aware that this setting is required.
Fix is to (re)use the `HELM_RELEASE` environment variable (something that users are already aware of) in our CI.
Addresses Issue #133

Eliminates duplicate CONJUR_OSS_HELM_RELEASE by using HELM_RELEASE

---

7_app_deploy.sh
8_app_verify_authentication.sh
kubernetes/test-app-with-outside-host-summon-init.yml
openshift/test-app-with-outside-host-summon-init.yml

The `test-app-with-host-outside-apps-branch-summon-init` flows exceeded the 63 char limit in OCP 4.7, leading to errors in the pipeline that looked like this:
```
[2021-05-13T18:47:47.852Z] deploymentconfig.apps.openshift.io/test-app-with-host-outside-apps-branch-summon-init created
[2021-05-13T18:47:47.852Z] The Route "test-app-with-host-outside-apps-branch-summon-init" is invalid: spec.host: Invalid value: "test-app-with-host-outside-apps-branch-summon-init-test-app-5-89f9f44a-2.apps.openshift-47-fips-enc.ci.conjur.net": host must conform to DNS 1123 naming conventions: [spec.host: Invalid value: "test-app-with-host-outside-apps-branch-summon-init-test-app-5-89f9f44a-2": must be no more than 63 characters]
```
In this PR, we update the name of those flows to something shorter. You can …

Shorten name of flow to get tests passing in OCP 4.7

---

ci/test

This change updates the version of Conjur OSS Helm chart that is used
in E2E testing from version `2.0.3` to `2.0.4`.

Updates Conjur OSS Helm chart to 2.0.4

---

2_admin_load_conjur_policies.sh
README.md
policy/templates/cluster-authn-svc-def.template.yml

This change adds two host IDs that can be used to validate basic authentication (i.e. no secrets access is required) with a Conjur instance. The two host IDs are intended for:
- Validating authentication with Conjur after the Kubernetes cluster has been configured for Conjur authn-k8s support
- Validating authentication with Conjur after an application Namespace has been configured for Conjur authn-k8s support
respectively.

Adds host IDs for validating basic authentication

---

Jenkinsfile
README.md
ci/secrets.yml

Remove support for testing against OCP v3.11 as it is now EoL and we are discontinuing support.
All references to v3.11 are removed including documentation and test tooling.
changes, or

Remove OpenShift v3.11 support

---

2_admin_load_conjur_policies.sh
Jenkinsfile
ci/test
exec-into-cli.sh
policy/load_policies.sh
rotate
set_env_vars.sh
utils.sh

Update demo to use CLI v8.0.
- Updated scripts and manifests to refer to the v8 Conjur CLI tag and use the updated command syntax.'
- Convert `load_policies.sh` script to use `sh` since new CLI container doesn't contain bash
- Use newly released version of the oss helm charts. (Depends on https://github.com/cyberark/conjur-oss-helm-chart/pull/180)
CyberArk internal issue ID: ONYX-33379
Depends on https://github.com/cyberark/kubernetes-conjur-deploy/pull/183
CHANGELOG update
changes, or

Use Conjur CLI v8.0

---

3_admin_init_conjur_cert_authority.sh
ci/Dockerfile
test_app_summon/Dockerfile
test_app_summon/Dockerfile.builder

There doesn't seem to be any real reason we're using the Ruby base image for the summon test app. Summon is written in Go, and besides we're installing the compiled version. The Ruby image is large and has therefore has a large attack surface and many packages with vulnerabilities. Switching to a slimmer base image such as Alpine reduces attack surface and vulnerabilities.
While testing this, I discovered that Jenkins tests on OpenShift were failing due to the google/cloud-sdk base image used in tests no longer having the correct glibc version needed by the OpenShift CLI. I decided to switch from the (very large) google/cloud-sdk image to a plain ubuntu image and download the Google Cloud CLI as described in https://cloud.google.com/sdk/docs/install#deb

CNJR-0000: Use alpine instead of Ruby base image
